apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-socket-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-sockets
  template:
    metadata:
      labels:
        app: go-sockets
    spec:
      containers:
        - name: go-sockets-container
          image: 194147442772.dkr.ecr.us-east-1.amazonaws.com/go-sockets
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
